class ForFixtures():
    USERVALUE = {"name": "Алексей","email": "nacharkin16@gmail.com","password": "nacharkin321"}

class TestValues():
    INGREDIENTS = {"ingredients": ["61c0c5a71d1f82001bdaaa6d","61c0c5a71d1f82001bdaaa70"]}
    FLUORESTENTIC_BUN = "Метеоритный флюоресцентный бургер"
    UNCORRECTED_INGREDIENT = {"ingredients": ["61c0c5a71d1f82001bdaaa68"]}
    MESSAGE_UFILLED_ID_INGREDIENTS = 'Ingredient ids must be provided'
    UNCORRECTED_INGREDIENT_ID_MESSAGE = "One or more ids provided are incorrect"
    USER_EXIST_MESSAGE = "User already exists"
    VALUES_IN_REQUIRED_FIELDS_EMPTY = 'Email, password and name are required fields'
    VALUES_FOR_AUTHORIZATION = {"email": "nacharkin16@gmail.com","password": "nacharkin321"}
    MESSAGE_UNCORRECT_VALUES_FOR_AUTHORIZATION = "email or password are incorrect"
    MESSAGE_SHOULD_AUTHORIZATION = "You should be authorised"
    RESPONSE_INGREDIENT_DATA = {'data': [{'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa6d',
           'calories': 643,
           'carbohydrates': 85,
           'fat': 26,
           'image': 'https://code.s3.yandex.net/react/code/bun-01.png',
           'image_large': 'https://code.s3.yandex.net/react/code/bun-01-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/bun-01-mobile.png',
           'name': 'Флюоресцентная булка R2-D3',
           'price': 988,
           'proteins': 44,
           'type': 'bun'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa6f',
           'calories': 420,
           'carbohydrates': 33,
           'fat': 244,
           'image': 'https://code.s3.yandex.net/react/code/meat-02.png',
           'image_large': 'https://code.s3.yandex.net/react/code/meat-02-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
           'name': 'Мясо бессмертных моллюсков Protostomia',
           'price': 1337,
           'proteins': 433,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa70',
           'calories': 2674,
           'carbohydrates': 300,
           'fat': 800,
           'image': 'https://code.s3.yandex.net/react/code/meat-04.png',
           'image_large': 'https://code.s3.yandex.net/react/code/meat-04-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/meat-04-mobile.png',
           'name': 'Говяжий метеорит (отбивная)',
           'price': 3000,
           'proteins': 800,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa71',
           'calories': 4242,
           'carbohydrates': 242,
           'fat': 142,
           'image': 'https://code.s3.yandex.net/react/code/meat-01.png',
           'image_large': 'https://code.s3.yandex.net/react/code/meat-01-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
           'name': 'Биокотлета из марсианской Магнолии',
           'price': 424,
           'proteins': 420,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa72',
           'calories': 30,
           'carbohydrates': 40,
           'fat': 20,
           'image': 'https://code.s3.yandex.net/react/code/sauce-02.png',
           'image_large': 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
           'name': 'Соус Spicy-X',
           'price': 90,
           'proteins': 30,
           'type': 'sauce'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa6e',
           'calories': 643,
           'carbohydrates': 85,
           'fat': 26,
           'image': 'https://code.s3.yandex.net/react/code/meat-03.png',
           'image_large': 'https://code.s3.yandex.net/react/code/meat-03-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
           'name': 'Филе Люминесцентного тетраодонтимформа',
           'price': 988,
           'proteins': 44,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa73',
           'calories': 14,
           'carbohydrates': 11,
           'fat': 22,
           'image': 'https://code.s3.yandex.net/react/code/sauce-04.png',
           'image_large': 'https://code.s3.yandex.net/react/code/sauce-04-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/sauce-04-mobile.png',
           'name': 'Соус фирменный Space Sauce',
           'price': 80,
           'proteins': 50,
           'type': 'sauce'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa74',
           'calories': 99,
           'carbohydrates': 42,
           'fat': 24,
           'image': 'https://code.s3.yandex.net/react/code/sauce-03.png',
           'image_large': 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
           'name': 'Соус традиционный галактический',
           'price': 15,
           'proteins': 42,
           'type': 'sauce'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa6c',
           'calories': 420,
           'carbohydrates': 53,
           'fat': 24,
           'image': 'https://code.s3.yandex.net/react/code/bun-02.png',
           'image_large': 'https://code.s3.yandex.net/react/code/bun-02-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
           'name': 'Краторная булка N-200i',
           'price': 1255,
           'proteins': 80,
           'type': 'bun'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa75',
           'calories': 100,
           'carbohydrates': 100,
           'fat': 99,
           'image': 'https://code.s3.yandex.net/react/code/sauce-01.png',
           'image_large': 'https://code.s3.yandex.net/react/code/sauce-01-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/sauce-01-mobile.png',
           'name': 'Соус с шипами Антарианского плоскоходца',
           'price': 88,
           'proteins': 101,
           'type': 'sauce'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa76',
           'calories': 986,
           'carbohydrates': 609,
           'fat': 689,
           'image': 'https://code.s3.yandex.net/react/code/mineral_rings.png',
           'image_large': 'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
           'name': 'Хрустящие минеральные кольца',
           'price': 300,
           'proteins': 808,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa77',
           'calories': 77,
           'carbohydrates': 55,
           'fat': 5,
           'image': 'https://code.s3.yandex.net/react/code/sp_1.png',
           'image_large': 'https://code.s3.yandex.net/react/code/sp_1-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
           'name': 'Плоды Фалленианского дерева',
           'price': 874,
           'proteins': 20,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa78',
           'calories': 189,
           'carbohydrates': 111,
           'fat': 432,
           'image': 'https://code.s3.yandex.net/react/code/core.png',
           'image_large': 'https://code.s3.yandex.net/react/code/core-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/core-mobile.png',
           'name': 'Кристаллы марсианских альфа-сахаридов',
           'price': 762,
           'proteins': 234,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa79',
           'calories': 6,
           'carbohydrates': 3,
           'fat': 2,
           'image': 'https://code.s3.yandex.net/react/code/salad.png',
           'image_large': 'https://code.s3.yandex.net/react/code/salad-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/salad-mobile.png',
           'name': 'Мини-салат Экзо-Плантаго',
           'price': 4400,
           'proteins': 1,
           'type': 'main'},
          {'__v': 0,
           '_id': '61c0c5a71d1f82001bdaaa7a',
           'calories': 3377,
           'carbohydrates': 420,
           'fat': 48,
           'image': 'https://code.s3.yandex.net/react/code/cheese.png',
           'image_large': 'https://code.s3.yandex.net/react/code/cheese-large.png',
           'image_mobile': 'https://code.s3.yandex.net/react/code/cheese-mobile.png',
           'name': 'Сыр с астероидной плесенью',
           'price': 4142,
           'proteins': 84,
           'type': 'main'}],
 'success': True}